### ISSUE TITLE
We must make sure not to use STP

### ISSUE THREAD

**Issue by phoracek** [RHsyseng/rhcos-slb#14]
With OVS it is disabled by default, but with Linux it would be enabled.

**Comment by kobi86** [comment]
Should we add this "bridge.stp no" to the script?  

Should we want to check the configuration and change the stp accordingly?

**Comment by phoracek** [comment]
I think we are safe leaving it as is with OVS, although setting it should not hurt. I opened this tracker so we make sure to address it while moving to Linux, where we have to be explicit.

**Comment by kobi86** [comment]
Will be implemented in linux-bridge git branch

**Comment by kobi86** [comment]
@phoracek I think we can close this issue on currently non-relevant

**Comment by phoracek** [comment]
Let's do that
