### ISSUE TITLE
Race in MAC configuration

### ISSUE THREAD

**Issue by phoracek** [RHsyseng/rhcos-slb#2]
Based on https://bugzilla.redhat.com/show_bug.cgi?id=1899745#c2, we may  need to drop `cloned-mac-address` from the bridge interface to avoid races.

**Comment by RamLavi** [comment]
is the race also relevant if we use `assigned-mac-address` instead of `cloned-mac-address` (`cloned-mac-address` is [deprecated](https://developer.gnome.org/NetworkManager/stable/settings-802-3-ethernet.html))?

**Comment by RamLavi** [comment]
also asked in the BZ

**Comment by kobi86** [comment]
Looks like the "assigned-mac-address"  only exists on D-Bus API 
"(Note that this property only exists in D-Bus API. libnm and nmcli continue to call this property "cloned-mac-address)"
so as long as we are on nm we are covered  :)

**Comment by RamLavi** [comment]
Should be fixed in #16

**Comment by phoracek** [comment]
Alas, as David pointed out in https://github.com/RHsyseng/rhcos-slb/pull/18#issuecomment-828649703, we can't

**Comment by kobi86** [comment]
Notice that the changes that we have done are effecting the scripts, the new script works on 4.7.z 
but NOT on 4.6.z

Checking some more configuration if we can make it work on both versions

**Comment by kobi86** [comment]
@phoracek is this issue still relevant?

**Comment by phoracek** [comment]
Nope, it was resolved via https://github.com/RHsyseng/rhcos-slb/commit/0276ae99e46deb8c935ecf5b9884cf44e0113fb6
