### ISSUE TITLE
proposal: Add ci to rhcos-slb

### ISSUE THREAD

**Issue by RamLavi** [RHsyseng/rhcos-slb#23]
Introduction:
Currently there are [coreos-ci](https://github.com/coreos/coreos-assembler/blob/main/mantle/kola/tests/misc/network.go#L53) test in place that runs [cosa](https://github.com/coreos/coreos-assembler) repo, to make sure the scripts runs smoothly with rhcos.

Goal:
We would like to have a ci on this repo, that will check the current `setup-ovs.sh` with the ci on coreos.
This way, every change to `setup-ovs.sh` will be smoke-tested before it is approved.

Method:
In order to avoid double dependency, the ci will:
- Clone the coreos-assembler repo
- Replace the `setup-ovs.sh` with the currently used on rhcos-slb's local directory 
- Run the coreos-assembler ci tests using the latest rhcos available

Note: we plan to run this test on every PR, with the help of [project-infra](https://github.com/kubevirt/project-infra)

**Comment by RamLavi** [comment]
added a WIP PR: https://github.com/RHsyseng/rhcos-slb/pull/24

**Comment by RamLavi** [comment]
CI [rehearsal](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_project-infra/1423/rehearsal-coreos-assembler-ci-network-tests-main/1414576954178277376) on prow looks good (including artifacts).

**Comment by phoracek** [comment]
@RamLavi could we silence the download progress bar?

```
919550K .......... .......... .......... .......... .......... 99%  129M 0s
919600K .......... .......... .......... .......... .......... 99% 76.9M 0s
919650K .......... .......... .......... .......... .......... 99%  117M 0s
919700K .......... .......... .......... .......... .......... 99%  129M 0s
919750K .......... .......... ....                            100%  184M=12s
```

It occupies most of the log and is not particularly useful

**Comment by phoracek** [comment]
And one nit - it would be nice to export junit.xml to get quick insight into the results.

Other than that, it's pretty cool!

**Comment by RamLavi** [comment]
> And one nit - it would be nice to export junit.xml to get quick insight into the results.
> 
> Other than that, it's pretty cool!

Added [PR](https://github.com/RHsyseng/rhcos-slb/pull/25) to remove the log clatter
Also [changed](https://github.com/kubevirt/project-infra/compare/4582568d0796d3cd735cc500f7769b085c67f7f6..cbc8952a0bbb0d63481fd034a2f2639ad60816e3) the project infra PR to not show the dnf install outputs.

**Comment by RamLavi** [comment]
@phoracek regarding the junit.xml, UUIC coreos ci does not support reporters in junit.xml format.
But they do output a test.tap file, and using this [tap-junit](https://www.npmjs.com/package/tap-junit) tool I can convert it to junit.xml
What do you think?

**Comment by RamLavi** [comment]
> That sounds good! Unless Prow supports native .tap file

unfortunately AFAIK [spyglass](https://github.com/kubernetes/test-infra/tree/master/prow/spyglass/lenses) does not support a tap Lens/plugin..
This is the PR: https://github.com/RHsyseng/rhcos-slb/pull/26 :)
